<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\shared\ExchangeRateViewer.Shared.Cqrs\ExchangeRateViewer.Shared.Cqrs.csproj" />
        <ProjectReference Include="..\..\shared\ExchangeRateViewer.Shared.Kernel\ExchangeRateViewer.Shared.Kernel.csproj" />
        <ProjectReference Include="..\ExchangeRateViewer.Finance.Domain\ExchangeRateViewer.Finance.Domain.csproj" />
    </ItemGroup>

</Project>
